name: Flutter Build & Release

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract zip file
        run: |
          unzip chat_yemen_2026_pro_finall.zip -d extracted_project
          PROJ_DIR=$(find extracted_project -name "pubspec.yaml" -exec dirname {} \;)
          echo "PROJECT_DIR=$PROJ_DIR" >> $GITHUB_ENV

      - name: Fix pubspec dependencies
        run: |
          cd ${{ env.PROJECT_DIR }}
          sed -i 's/nearby_connections: ^5.0.0/nearby_connections: any/g' pubspec.yaml
          sed -i 's/flutter_riverpod: .*/flutter_riverpod: any/g' pubspec.yaml
          
          # استبدال اصدار cryptography بشكل صحيح داخل مجلد الاعتماديات
          sed -i 's/cryptography:.*/cryptography: 2.0.5/g' pubspec.yaml
          rm -f pubspec.lock

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies & Repairs Android files
        run: |
          cd ${{ env.PROJECT_DIR }}
          flutter create . --platforms=android
          flutter pub add cryptography:2.0.5
          flutter pub get

      - name: Build APK
        run: |
          cd ${{ env.PROJECT_DIR }}
          flutter build apk --release --no-tree-shake-icons

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: ${{ env.PROJECT_DIR }}/build/app/outputs/flutter-apk/app-release.apk
